#pragma kernel CSMain

Texture2D<float4> Target;
Texture2D<float4> Current;
Texture2D<float4> CandidateShape;
RWStructuredBuffer<uint> Result;

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    uint width, height;
    Target.GetDimensions(width, height);

    //if (id.x >= width || id.y >= height)
    //    return;

    float4 t = Target[id.xy];

    float3 blended =
        lerp(Current[id.xy].rgb,
             CandidateShape[id.xy].rgb,
             CandidateShape[id.xy].a);

    float diff = max(max(abs(t.r - blended.r),
                         abs(t.g - blended.g)),
                         abs(t.b - blended.b));

    InterlockedAdd(Result[0], (uint) (diff * 255.0));
}